server:
  port:
    80

spring:
  datasource:
    druid:
      time-between-eviction-runs-millis: 300000
      #mysql数据源，主数据源
      master:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.12.45:3306/bjtu_atv?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&connectTimeout=30000&socketTimeout=60000
#        url: jdbc:mysql://101.254.248.181:3306/bjtu_atv?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: Ggtbj2023!
      #postgreSQL数据源，图形数据源
      slave:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.12.54:6543/bjtu_atv_gloc
        username: postgres
        password: Caupd@12345

  redis:
    host: 192.168.12.45
    port: 6379
    password: 123456

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mvc:
    path match:
      matching-strategy: ant-path-matcher

swagger:
  production: false
  basic:
    enable: true
    username: admin
    password: 123456

mybatis:
  mapper-locations: classpath:**/*.xml

logging:
  level:
    com:
      example: debug


  ## local-imgUrl
  #imgPath: /Users/yanxinzhao/Desktop/atv-qu/smokeManagement/img/

## linux-imgUrl
imgPath: /home/img/

## linux-imgHost
imgHost: http://tjm.caupdcloud.com/img/

## image-server
host: 192.168.12.45
sshport: 22
username: ftpuser
password: qwe123!@#