server:
  port:
    80

spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    #druid:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.12.45:3306/bjtu_atv?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://127.0.0.1:3306/bjtu_atv?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: yxz09179012
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mvc:
    path match:
      matching-strategy: ant-path-matcher

swagger:
  production: false
  basic:
    enable: true
    username: admin
    password: 123456

mybatis:
  mapper-locations: classpath:**/*.xml

logging:
  level:
    com:
      example: debug

  
## local-imgUrl
#imgPath=/Users/yanxinzhao/Desktop/atv-qu/smokeManagement/img/
  
## linux-imgUrl
imgPath: /home/img/
  
## linux-imgHost
imgHost: http://tjm.caupdcloud.com/img/